//! Windowed, id-keyed artwork for the Local Library (the perf contract:
//! a 16K-track library must never decode a cover it does not show).
//!
//! Split out of `local_library_qt.rs` (phase-24 modularization) and made
//! source-aware. The routing decision is NOT made here — `artwork_qt::classify`
//! owns the one url taxonomy the whole app shares (see its module docs), so a
//! cover resolves identically in the grid, the queue and the now-playing bar:
//!
//!  - a LOCAL cover path resolves to the `qbz-library` THUMBNAIL (generated
//!    once, cached on disk) — never the full-size original, which is what
//!    keeps a 16K library from decoding 3000px jpegs into cards;
//!  - a PLEX thumb (`/library/...` / `/photo/...`) resolves to the tokenized
//!    server-side transcode URL and is served through the SAME shared image
//!    cache the Home/queue covers use (`artwork_qt`), at the SAME transcode
//!    size (`artwork_qt::PLEX_THUMB_PX`), so a Plex cover is downloaded once
//!    for the whole process and then read from disk like any other;
//!  - an http(s) cover (an offline-download row that kept its CDN url) goes
//!    down the same disk-cache path as a Plex thumb.
//!
//! Every arm ends at a `file://` path — QML `Image` decodes it natively and
//! asynchronously, and no token ever reaches QML.
//!
//! # Why the pass is split cheap/cold (the 15-second bug)
//!
//! The pass used to be one blocking sweep that emitted its hits as ONE batch
//! at the end. On a FIRST visit — where every cover still has to be decoded
//! and downscaled — nothing appeared until the last card in the window had
//! resolved, so a warm-looking grid sat blank for ~15 s and then filled in one
//! lump. The pass is now two phases:
//!
//!  1. [`resolve_window_blocking`] — the CHEAP phase. Memo lookups, one
//!     `stat` per key, no decode. Everything already on disk comes back in
//!     `hits` (emitted at once, within a frame or two); everything that still
//!     needs a decode comes back in `cold`, in the caller's display order.
//!  2. [`stream_cold`] — the EXPENSIVE phase. A bounded pool of blocking
//!     workers pulls from a shared cursor, so covers are STARTED in display
//!     order (row 1 before row 40) and each one is emitted through the
//!     id-keyed signal the moment IT resolves. Covers now appear progressively
//!     instead of in one lump, and the window finishes ~[`GEN_WORKERS`]×
//!     faster because the decodes overlap.
//!
//! Two memos keep a revisit nearly free: [`THUMBS`] (source path -> generated
//! thumbnail) so the second visit skips `get_or_generate_thumbnail` entirely,
//! and `artwork_qt`'s own memo on the Plex/http arm. A first visit whose
//! thumbnails were generated by an earlier RUN is also cheap — the phase-1
//! `stat` on the thumbnail path finds them and seeds the memo.
//!
//! `qbz_library::generate_thumbnail` writes the jpeg straight to its final
//! path (no temp+rename), so two workers must never generate the SAME source
//! concurrently — overlapping windows share most of their keys and would race
//! into a half-written file. [`GEN_LOCKS`] serializes per source path; the
//! loser of the race then finds the file on disk and returns immediately.

use std::collections::hash_map::DefaultHasher;
use std::collections::{HashMap, HashSet};
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, LazyLock, Mutex, RwLock};

use crate::artwork_qt::{self, ArtUrl};
use crate::local_state::state;

/// Memo ceiling, mirroring `artwork_qt::MEMO_CAP`: an accelerator, cleared
/// wholesale rather than carrying LRU bookkeeping.
const MEMO_CAP: usize = 8192;

/// Blocking workers that decode+downscale cold covers in parallel. Four is
/// deliberate: it is the point where a window of ~50 covers stops being the
/// user-visible wait, while the peak resident set stays at four decoded
/// bitmaps (a 3000px jpeg is ~36 MB decoded) rather than one per core.
const GEN_WORKERS: usize = 8;

/// Per-source generation locks, sharded. 64 shards keeps false sharing
/// between unrelated covers negligible at [`GEN_WORKERS`] × a few overlapping
/// windows, without carrying a map of live entries.
const GEN_SHARDS: usize = 64;

/// Cover source path -> its generated thumbnail. See the module docs.
static THUMBS: LazyLock<RwLock<HashMap<String, PathBuf>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

static GEN_LOCKS: LazyLock<Vec<Mutex<()>>> =
    LazyLock::new(|| (0..GEN_SHARDS).map(|_| Mutex::new(())).collect());

fn gen_shard(src: &str) -> usize {
    let mut h = DefaultHasher::new();
    src.hash(&mut h);
    (h.finish() as usize) % GEN_SHARDS
}

/// The result of the cheap phase of one window pass.
pub struct ArtworkWindow {
    /// (artKey, "file://…") — already on disk, ready to emit immediately.
    pub hits: Vec<(String, String)>,
    /// (artKey, fetchable http url) — not on disk yet; the bridge downloads
    /// these off the Qt thread and re-resolves them to `file://`. Named for
    /// its dominant case; an http cover on a Plex-less row lands here too.
    pub plex_misses: Vec<(String, String)>,
    /// (artKey, local cover path) — needs a decode+downscale, in the caller's
    /// display order. Fed to [`stream_cold`], which emits each one as it
    /// lands instead of batching them.
    pub cold: Vec<(String, String)>,
}

/// Cheap phase: resolve everything that costs no more than a `stat`, and
/// triage the rest. BLOCKING (disk `stat`s) but never decodes — the bridge
/// runs it on `spawn_blocking` and can emit `hits` within a frame or two.
/// Keys with no cover are dropped, so the QML map only ever grows with real
/// hits.
pub fn resolve_window_blocking(keys: Vec<String>) -> ArtworkWindow {
    let sources: Vec<(String, String)> = state(|s| {
        keys.iter()
            .filter_map(|k| s.art_index.get(k).map(|p| (k.clone(), p.clone())))
            .collect()
    });
    let mut hits = Vec::with_capacity(sources.len());
    let mut plex_misses = Vec::new();
    let mut cold = Vec::new();
    let mut seen: HashSet<String> = HashSet::new();
    for (key, src) in sources {
        if !seen.insert(key.clone()) {
            continue;
        }
        match artwork_qt::classify(&src) {
            // --- Plex / remote arm: disk cache, else a background fetch ----
            ArtUrl::Plex(_) | ArtUrl::Http(_) => {
                let cached = artwork_qt::cached_path(&src);
                if cached.is_empty() {
                    // Hand the bridge the RAW source: `download_missing`
                    // re-classifies it, and `cached_path` memoizes under the
                    // raw url, so the re-resolve below is a RAM read.
                    plex_misses.push((key, src));
                } else {
                    hits.push((key, cached));
                }
            }
            // No server / token: nothing to fetch, leave the card blank.
            ArtUrl::PlexUnconfigured | ArtUrl::Empty => {}
            // --- Local arm: thumbnail the on-disk cover -------------------
            ArtUrl::LocalFile(path) => match cached_thumbnail(&path) {
                Some(thumb) => hits.push((key, artwork_qt::file_url(&thumb.to_string_lossy()))),
                // Not on disk (or gone): decode it in phase 2. `cold` keeps
                // the caller's order, which is display order.
                None => cold.push((key, path)),
            },
        }
    }
    ArtworkWindow {
        hits,
        plex_misses,
        cold,
    }
}

/// Expensive phase: generate the cold thumbnails on a bounded pool and emit
/// each `(key, "file://…")` through `emit` AS IT RESOLVES — that is what makes
/// covers appear progressively instead of in one lump.
///
/// Workers pull from a shared cursor, so item 0 (the top of the reported
/// window) is always started first and no worker idles behind a slow decode.
/// `emit` is a plain fn pointer so it carries no lifetime into the blocking
/// pool; the bridge passes its per-cover signal emitter.
pub async fn stream_cold(cold: Vec<(String, String)>, emit: fn(String, String)) {
    if cold.is_empty() {
        return;
    }
    let workers = GEN_WORKERS.min(cold.len());
    let cold = Arc::new(cold);
    let cursor = Arc::new(AtomicUsize::new(0));
    let mut handles = Vec::with_capacity(workers);
    for _ in 0..workers {
        let cold = Arc::clone(&cold);
        let cursor = Arc::clone(&cursor);
        handles.push(tokio::task::spawn_blocking(move || loop {
            let i = cursor.fetch_add(1, Ordering::Relaxed);
            let Some((key, src)) = cold.get(i) else {
                return;
            };
            if let Some(thumb) = local_thumbnail(src) {
                emit(key.clone(), artwork_qt::file_url(&thumb.to_string_lossy()));
            }
        }));
    }
    for h in handles {
        let _ = h.await;
    }
}

/// The thumbnail for a local cover IF it costs nothing: the memo, else one
/// `stat` on the thumbnail path (which is where a previous run's thumbnails
/// live). `None` means "must be generated" — the caller defers it to phase 2.
fn cached_thumbnail(src: &str) -> Option<PathBuf> {
    // A local cover is very often ALREADY the thumbnail the scanner generated.
    // Re-hashing its path yields a DIFFERENT filename, so the cold phase decodes
    // it, Lanczos-resizes it to its own size (a null scale) and re-encodes a
    // byte-identical-looking duplicate — that is most of the wait before the
    // first cover appears.
    if let Ok(dir) = qbz_library::get_thumbnails_dir() {
        let p = std::path::Path::new(src);
        if p.starts_with(&dir) && p.is_file() {
            return Some(p.to_owned());
        }
    }
    if let Ok(memo) = THUMBS.read() {
        if let Some(hit) = memo.get(src) {
            if hit.is_file() {
                return Some(hit.clone());
            }
        }
    }
    let thumb = qbz_library::get_thumbnail_path(Path::new(src)).ok()?;
    if !thumb.is_file() {
        return None;
    }
    memoize(src, &thumb);
    Some(thumb)
}

/// The thumbnail for a local cover, generating it if needed. Falls back to
/// the original file when no thumbnail can be produced (unsupported source)
/// so the card is not blank; `None` only when the cover itself is gone.
fn local_thumbnail(src: &str) -> Option<PathBuf> {
    if let Some(hit) = cached_thumbnail(src) {
        return Some(hit);
    }
    let path = Path::new(src);
    if !path.is_file() {
        return None;
    }
    // Serialize same-source generation (see the module docs): the loser of
    // the race re-checks the memo and returns without decoding anything.
    let guard = GEN_LOCKS[gen_shard(src)]
        .lock()
        .unwrap_or_else(|e| e.into_inner());
    if let Some(hit) = cached_thumbnail(src) {
        drop(guard);
        return Some(hit);
    }
    let resolved = qbz_library::get_or_generate_thumbnail(path).unwrap_or_else(|_| path.to_owned());
    drop(guard);
    memoize(src, &resolved);
    Some(resolved)
}

fn memoize(src: &str, resolved: &Path) {
    if let Ok(mut memo) = THUMBS.write() {
        if memo.len() >= MEMO_CAP {
            memo.clear();
        }
        memo.insert(src.to_string(), resolved.to_owned());
    }
}

/// Download the misses into the shared image cache and return the resolved
/// `(key, file://…)` pairs. Async (network) — the bridge awaits it on the
/// tokio runtime, never on the Qt thread.
pub async fn fetch_plex_misses(misses: Vec<(String, String)>) -> Vec<(String, String)> {
    if misses.is_empty() {
        return Vec::new();
    }
    let urls: Vec<String> = misses.iter().map(|(_, u)| u.clone()).collect();
    artwork_qt::download_missing(urls).await;
    misses
        .into_iter()
        .filter_map(|(key, url)| {
            let path = artwork_qt::cached_path(&url);
            (!path.is_empty()).then_some((key, path))
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Large art tier (contract 2026-08-15-immersive-completion 04 §5, ruling 6)
// ---------------------------------------------------------------------------

/// The 1600px-tier art for a big slot (immersive main art, SPLIT, lightbox),
/// resolved ON DEMAND. `src` is the track's raw art source (the DB's
/// `artwork_path` — usually the 500px thumb; sometimes an original cover file
/// when the folder-cover fallback served it directly). `track_id` is the
/// local-library rowid, needed to re-open the source when `src` is only the
/// thumb: embedded picture bytes out of the audio file first (the scanner's
/// precedence, scan.rs:130), then the folder-art heuristic. If the original
/// fits inside `qbz_library::LARGE_ART_PX` the native file is served — never
/// an upscale. When every re-open fails, the 500px thumb itself is returned:
/// it is the best art that exists for this track.
///
/// BLOCKING (one DB read, then possibly a decode) — call from
/// `spawn_blocking`. Lists never come here: they keep the 500px tier.
pub fn large_art_blocking(src: &str, track_id: Option<u64>) -> Option<PathBuf> {
    let path = Path::new(src);
    if !path.is_file() {
        return None;
    }
    let is_thumb = qbz_library::get_thumbnails_dir()
        .map(|dir| path.starts_with(dir))
        .unwrap_or(false);
    if !is_thumb {
        // An original cover file: bound it (native size served as-is when it
        // already fits).
        return qbz_library::get_or_generate_large_thumbnail(path).ok();
    }
    // `src` is a 500px thumb — its hash is one-way, so the original is
    // re-derived from the track row.
    let Some(track) = track_id.and_then(|id| {
        crate::local_state::with_db(|db| db.get_track(id as i64)).flatten()
    }) else {
        return Some(path.to_path_buf());
    };
    // Serialize per source (the module-docs race): the large tier shares the
    // 500px tier's hash key, so the same lock shard covers both.
    let guard = GEN_LOCKS[gen_shard(src)]
        .lock()
        .unwrap_or_else(|e| e.into_inner());
    let out = large_art_for_track(&track).or_else(|| Some(path.to_path_buf()));
    drop(guard);
    out
}

/// Embedded bytes first (the scanner's precedence), folder art second.
fn large_art_for_track(track: &qbz_library::LocalTrack) -> Option<PathBuf> {
    let file = Path::new(&track.file_path);
    if let Some(bytes) = qbz_library::MetadataExtractor::extract_artwork_bytes(file) {
        if let Ok(p) =
            qbz_library::get_or_generate_large_thumbnail_from_bytes(&bytes, &track.file_path)
        {
            return Some(p);
        }
    }
    let art = qbz_library::MetadataExtractor::find_folder_artwork(file, Some(&track.album))?;
    qbz_library::get_or_generate_large_thumbnail(Path::new(&art)).ok()
}
