[package]
name = "qbz-disc"
version.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
sha1 = "0.10"
base64 = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
reqwest = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs"] }
